### ISSUE TITLE
CUDA driver library cannot be found

### ISSUE THREAD

**Issue by chintan-donda** [outerbounds/dolly-metaflow#1]
I'm trying to run `python test_gpu_setup.py run --with kubernetes`

But it fails with error:
```
2023-05-10 15:12:14.690 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l] WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
2023-05-10 15:12:14.692 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l] WARNING: You are using pip version 22.0.4; however, version 23.1.2 is available.
2023-05-10 15:12:14.692 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l] You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
2023-05-10 15:12:19.224 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l] WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
2023-05-10 15:12:19.227 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l] WARNING: You are using pip version 22.0.4; however, version 23.1.2 is available.
2023-05-10 15:12:19.227 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l] You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
2023-05-10 15:12:19.795 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l] Overriding of current TracerProvider is not allowed
2023-05-10 15:12:19.795 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l] Attempting to instrument while already instrumented
2023-05-10 15:12:19.801 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l] Traceback (most recent call last):
2023-05-10 15:12:19.801 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l]   File "/metaflow/metaflow/multicore_utils.py", line 46, in _spawn
2023-05-10 15:12:19.801 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l]     ret = func(arg)
2023-05-10 15:12:19.801 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l]   File "/metaflow/metaflow/multicore_utils.py", line 89, in wrapper
2023-05-10 15:12:19.801 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l]     return idx, func(arg)
2023-05-10 15:12:19.801 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l]   File "/metaflow/test_gpu_setup.py", line 64, in <lambda>
2023-05-10 15:12:19.801 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l]     parallel_map(lambda x: cudatest.push_cuda(**x), params)
2023-05-10 15:12:19.801 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l]   File "/metaflow/cudatest.py", line 13, in push_cuda
2023-05-10 15:12:19.801 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l]     cuda.select_device(device)
2023-05-10 15:12:19.801 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l]   File "/usr/local/lib/python3.9/site-packages/numba/cuda/api.py", line 437, in select_device
2023-05-10 15:12:19.801 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l]     context = devices.get_context(device_id)
2023-05-10 15:12:19.801 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l]   File "/usr/local/lib/python3.9/site-packages/numba/cuda/cudadrv/devices.py", line 220, in get_context
2023-05-10 15:12:19.801 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l]     return _runtime.get_or_create_context(devnum)
2023-05-10 15:12:19.801 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l]   File "/usr/local/lib/python3.9/site-packages/numba/cuda/cudadrv/devices.py", line 144, in get_or_create_context
2023-05-10 15:12:19.801 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l]     return self._activate_context_for(devnum)
2023-05-10 15:12:19.801 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l]   File "/usr/local/lib/python3.9/site-packages/numba/cuda/cudadrv/devices.py", line 176, in _activate_context_for
2023-05-10 15:12:19.801 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l]     gpu = self.gpus[devnum]
2023-05-10 15:12:19.801 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l]   File "/usr/local/lib/python3.9/site-packages/numba/cuda/cudadrv/devices.py", line 40, in __getitem__
2023-05-10 15:12:19.801 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l]     return self.lst[devnum]
2023-05-10 15:12:19.801 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l]   File "/usr/local/lib/python3.9/site-packages/numba/cuda/cudadrv/devices.py", line 26, in __getattr__
2023-05-10 15:12:19.801 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l]     numdev = driver.get_device_count()
2023-05-10 15:12:19.801 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l]   File "/usr/local/lib/python3.9/site-packages/numba/cuda/cudadrv/driver.py", line 437, in get_device_count
2023-05-10 15:12:19.801 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l]     self.cuDeviceGetCount(byref(count))
2023-05-10 15:12:19.801 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l]   File "/usr/local/lib/python3.9/site-packages/numba/cuda/cudadrv/driver.py", line 308, in __getattr__
2023-05-10 15:12:19.801 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l]     raise CudaSupportError("Error at driver init: \n%s:" %
2023-05-10 15:12:19.801 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l] numba.cuda.cudadrv.error.CudaSupportError: Error at driver init:
2023-05-10 15:12:19.801 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l]
2023-05-10 15:12:19.801 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l] CUDA driver library cannot be found.
2023-05-10 15:12:19.801 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l] If you are sure that a CUDA driver is installed,
2023-05-10 15:12:19.801 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l] try setting environment variable NUMBA_CUDA_DRIVER
2023-05-10 15:12:19.801 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l] with the file path of the CUDA driver shared library.
2023-05-10 15:12:19.801 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l] :
2023-05-10 15:12:19.804 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l] <flow TestDollyGPUSetup step train> failed:
2023-05-10 15:12:21.903 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l]     Internal error
2023-05-10 15:12:30.577 [29/train/87 (pid 1652)] Kubernetes error:
2023-05-10 15:12:30.577 [29/train/87 (pid 1652)] Error (exit code 1). This could be a transient error. Use @retry to retry.
2023-05-10 15:12:30.657 [29/train/87 (pid 1652)] 
2023-05-10 15:12:21.903 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l] Traceback (most recent call last):
2023-05-10 15:12:21.903 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l]   File "/metaflow/metaflow/cli.py", line 1175, in main
2023-05-10 15:12:21.903 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l]     start(auto_envvar_prefix="METAFLOW", obj=state)
2023-05-10 15:12:21.903 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l]   File "/metaflow/metaflow/tracing_otel.py", line 131, in wrapper_func
2023-05-10 15:12:21.903 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l]     return func(args, kwargs)
2023-05-10 15:12:21.903 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l]   File "/metaflow/metaflow/_vendor/click/core.py", line 829, in __call__
2023-05-10 15:12:21.903 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l]     return self.main(args, kwargs)
2023-05-10 15:12:21.903 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l]   File "/metaflow/metaflow/_vendor/click/core.py", line 782, in main
2023-05-10 15:12:21.903 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l]     rv = self.invoke(ctx)
2023-05-10 15:12:21.903 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l]   File "/metaflow/metaflow/_vendor/click/core.py", line 1259, in invoke
2023-05-10 15:12:21.903 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l]     return _process_result(sub_ctx.command.invoke(sub_ctx))
2023-05-10 15:12:21.903 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l]   File "/metaflow/metaflow/_vendor/click/core.py", line 1066, in invoke
2023-05-10 15:12:21.903 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l]     return ctx.invoke(self.callback, ctx.params)
2023-05-10 15:12:21.903 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l]   File "/metaflow/metaflow/_vendor/click/core.py", line 610, in invoke
2023-05-10 15:12:21.903 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l]     return callback(args, kwargs)
2023-05-10 15:12:21.903 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l]   File "/metaflow/metaflow/_vendor/click/decorators.py", line 21, in new_func
2023-05-10 15:12:21.903 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l]     return f(get_current_context(), args, kwargs)
2023-05-10 15:12:21.903 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l]   File "/metaflow/metaflow/cli.py", line 582, in step
2023-05-10 15:12:21.903 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l]     task.run_step(
2023-05-10 15:12:21.903 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l]   File "/metaflow/metaflow/task.py", line 599, in run_step
2023-05-10 15:12:21.903 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l]     self._exec_step_function(step_func)
2023-05-10 15:12:21.903 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l]   File "/metaflow/metaflow/task.py", line 60, in _exec_step_function
2023-05-10 15:12:21.903 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l]     step_function()
2023-05-10 15:12:21.903 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l]   File "/metaflow/my_decorators.py", line 412, in wrapper
2023-05-10 15:12:21.903 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l]     return function(args, kwargs)
2023-05-10 15:12:21.903 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l]   File "/metaflow/my_decorators.py", line 197, in func
2023-05-10 15:12:21.903 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l]     f(s)
2023-05-10 15:12:21.903 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l]   File "/metaflow/test_gpu_setup.py", line 64, in train
2023-05-10 15:12:21.903 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l]     parallel_map(lambda x: cudatest.push_cuda(x), params)
2023-05-10 15:12:21.904 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l]   File "/metaflow/metaflow/multicore_utils.py", line 92, in parallel_map
2023-05-10 15:12:21.904 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l]     return [r for idx, r in sorted(res)]
2023-05-10 15:12:21.904 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l]   File "/metaflow/metaflow/multicore_utils.py", line 75, in parallel_imap_unordered
2023-05-10 15:12:21.904 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l]     raise MulticoreException("Child failed")
2023-05-10 15:12:21.904 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l] metaflow.multicore_utils.MulticoreException: Child failed
2023-05-10 15:12:21.904 [29/train/87 (pid 1652)] [pod t-z5c62-k8s7l]
2023-05-10 15:12:30.841 [29/train/87 (pid 1652)] Task failed.
2023-05-10 15:12:31.010 Workflow failed.
2023-05-10 15:12:31.010 Terminating 0 active tasks...
2023-05-10 15:12:31.010 Flushing logs...
    Step failure:
    Step train (task-id 87) failed.
``` 

Earlier I was getting below errors:
`ModuleNotFoundError: No module named 'numba'`  => I’ve fixed this by using @pip decorator in the script, and it worked.
```
@pip(libraries={
        "numpy": "1.24.3",
        "numba": "0.57.0"
    })
    @resources(cpu=N_CPU, gpu=N_GPU, memory=MEMORY)
    @gpu_profile(interval=1)
    @step
    def train(self):
```

NOTE: I'm running from local machine on Outerbounds platform.

Any help pls?

**Comment by chintan-donda** [comment]
Also how can I run `python train_dolly.py run ` for just 10/50 iterations instead of a full 1 epoch?

**Comment by emattia** [comment]
> Also how can I run `python train_dolly.py run` for just 10/50 iterations instead of a full 1 epoch?

To run partial epochs, use the `sample-percentage` flow parameter. This passes on a number in 0 and 1 to the [`datasets.Dataset.train_test_split` function](https://huggingface.co/docs/datasets/v2.12.0/en/package_reference/main_classes#datasets.Dataset.train_test_split).

**Comment by tylerpotts** [comment]
@chintan-donda GPUs are a bit tricky to setup

You need to run a custom image with the CUDA drivers installed. I wasn't able to find an image with both CUDA and python installed, so I created this one based on the tensorflow image

```
FROM tensorflow/tensorflow:2.12.0-gpu

RUN apt update && apt install -y curl python3 python3-pip wget

RUN wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh
RUN bash ~/miniconda.sh -b
RUN rm ~/miniconda.sh

RUN /root/miniconda3/bin/conda init && cp /root/.bashrc /root/.bash_profile

RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 10 && \
    update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 10

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
```

I pushed this to an amazon elastic container registry and then ran it with `METAFLOW_DEFAULT_CONTAINER_IMAGE=<ECR_IMAGE_TAG> python metaflow_file.py run`
